authorName: default
experimentName: example_experiment
trialConcurrency: 2
maxExecDuration: 1h
maxTrialNum: 10
trainingServicePlatform: local
searchSpacePath: /git/Time-Series-Library/scripts/beigang_script/search_space.json
tuner:
  builtinTunerName: TPE
trial:
  command: python3  /git/Time-Series-Library/run_nni.py
  codeDir: .
  gpuNum: 0
useAnnotation: false
